name: _prototypeweatherapi_ci

# Trigger on pull request to push feature, push main and pull request main
on:
  push:
    branches:
      - main

# Set environment variables with anything needed by the pipeline

jobs:

  # For Pull Request
  runt_test:
    name: "Run application unit test."
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      